### ISSUE TITLE
kraken.exceptions.KrakenException.KrakenInvalidNonceError: An invalid nonce was supplied.

### ISSUE THREAD

**Issue by andyDoucette** [btschwertfeger/python-kraken-sdk#114]
I'm getting InvalidNonceErrors when I'm calling Trade().create_order().  

```
  File "/cs/crypto_sage/kraken/spot/trade/__init__.py", line 337, in create_order
    return self._request(  # type: ignore[return-value]
  File "/cs/crypto_sage/kraken/base_api/__init__.py", line 245, in _request
    return self.__check_response_data(
  File "/cs/crypto_sage/kraken/base_api/__init__.py", line 303, in __check_response_data
    return self.__err_handler.check(data)  # type: ignore[arg-type]
  File "/cs/crypto_sage/kraken/base_api/__init__.py", line 60, in check
    raise exception(data)
kraken.exceptions.KrakenException.KrakenInvalidNonceError: An invalid nonce was supplied.
```

I am running a single thread, single process for this API key.  I have another process using a different API key but they should be independent.  

The sdk code I'm using is based off of 1fce745.  I'm not sure if the nonce logic has changed since then or not.

Could there be an issue with the nonce logic?  Are you using system time to the microsecond?

**Comment by btschwertfeger** [comment]
According to the commit you provided, this is where the nonce is calculated: https://github.com/btschwertfeger/python-kraken-sdk/blob/1fce7454721b7fd4919a49eef4979b762db1a453/kraken/base_api/__init__.py#L199-L200

Indeed, the nonce is always API key independent and must be the highest ever sent for this key. 

I'm running several deployments using different API keys and did not experienced any nonce related errors, these were only a problem in a very early version of this tool. 

You can check the behaviour by running multiple instances using different and some with the same API keys and access endpoints that need authentication. Only those with the same key that are executed in nearly the same time but with some internal delay could lead to this error.

**Comment by andyDoucette** [comment]
That looks to me to just be millisecond accuracy.  Maybe two calls are happening within 1ms and getting the same nonce?  I remember from some earlier projects that ms accuracy wasn't enough for my logging, I needed us accuracy to not have re-use of timestamps.

**Comment by andyDoucette** [comment]
Do you have any concerns about using *1000000 instead of *1000?

**Comment by btschwertfeger** [comment]
I increased the accuracy of the nonce calculation for Spot and Futures in https://github.com/btschwertfeger/python-kraken-sdk/pull/106)](https://github.com/btschwertfeger/python-kraken-sdk/pull/106. This will be included in the upcoming release ([milestone/7](https://github.com/btschwertfeger/python-kraken-sdk/milestone/7)).

**Comment by andyDoucette** [comment]
Thanks so much! :)  I appreciate how well you're managing this project.  You really seem on top of things. :)
