### ISSUE TITLE
Add async REST API

### ISSUE THREAD

**Issue by Trevypants** [btschwertfeger/python-kraken-sdk#228]
**Describe the solution you'd like**

First of all, thank you for making such a clean Kraken client library. It is really refreshing to see. However, when investigating your code, I noticed that you are using the standard requests library which only supports synchronous API calls. Since we are working with API calls that I/O bound, asynchronous API calls would really help speed up applications that need to make many API calls at once.

There are many asynchronous libraries out there that could replace requests. For example [httpx](https://www.python-httpx.org/) offers both synchronous and asynchronous support. Or alternatively [aiohttp](https://docs.aiohttp.org/en/stable/) which is found to be faster than httpx but only supports async.

**Describe alternatives you've considered**

Here is another Kraken Python client library that supports async: [kraky](https://github.com/Atem18/kraky).

**Comment by btschwertfeger** [comment]
Hey @Trevypants, great idea! I'll have a look into it.
