### ISSUE TITLE
Feature proposal: Add proxy support

### ISSUE THREAD

**Issue by Graeme22** [btschwertfeger/python-kraken-sdk#256]
Hi, thanks for this cool project!

One feature that is missing, which would be extremely easy to add, is proxies. Many people use them for anonymity, which is a good use case. In my case, I'd like to use a proxy to improve security by routing traffic through a specific IP and whitelisting that IP for API usage.

**Describe the solution you'd like**

Pretty straightforward: `requests` already supports this, so it's as simple as passing the argument through the constructors.

If desired I can submit a PR with the proposed changes for spot and futures REST clients.

**Comment by btschwertfeger** [comment]
Hallo @Graeme22, thank you for your suggestion. I will have a look into it myself and let you know!

**Comment by btschwertfeger** [comment]
Yeah that looks fine, feel free to open a PR!
