### ISSUE TITLE
Populate OrderBook with current state when add_book is called

### ISSUE THREAD

**Issue by OpenCoderX** [btschwertfeger/python-kraken-sdk#267]
I've created an order book client for a slowly moving market so it can be a long time until we receive a change to the orderbook. When that happens, there is no call to on_book_update callback and we end up with an empty orderbook in the downstream system. 

What does the team think about updating the orderbook with the current state of the orderbook , calling on_book_update with this initial state to emit an initial event when add_book is called. 

This would avoid the situation where we know there are orders in the odrerbook but there have been no changes to the order book with would trigger the on_book_update callback?

**Comment by btschwertfeger** [comment]
Hello @OpenCoderX, do you have a reproducible example? As far as I can see is the initial snapshot already respected and `on_book_update` is called, as soon as the initial snapshot is processed (see https://github.com/btschwertfeger/python-kraken-sdk/blob/v3.1.0/kraken/spot/orderbook.py#L194-L213). 

Meaning that the book is only empty for a really short time.

**Comment by btschwertfeger** [comment]
@OpenCoderX, could you verify that your issue does not exist with the latest versions?

**Comment by btschwertfeger** [comment]
Closing the issue, as the it seems like there is no problem anymore.
