### ISSUE TITLE
SpotAsyncClient can not be imported

### ISSUE THREAD

**Issue by flynn1973** [btschwertfeger/python-kraken-sdk#292]
**Describe the bug**
I installed with pip, but when i tried to import SpotAsyncClient an error is shown.

````
from kraken.spot import SpotAsyncClient
ImportError: cannot import name 'SpotAsyncClient' from 'kraken.spot' (/opt/freeware/lib/python3.9/site-packages/kraken/spot/__init__.py)
````

**To Reproduce**

1.  from kraken.spot import SpotAsyncClient

**Expected behavior**
As i strictly followed the docs, i expect importing SpotAsyncClien is possible

**Screenshots and code snippets**
If applicable, add screenshots or code snippets to help explain your problem.

**Environment (please complete the following information):**

- OS: AIX
- Python 3.11

**Additional context**
i checked spot/__init__.py, no SpotAsyncClient. not sure why...

````
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger

"""Module that provides the Spot REST clients and utility functions."""

# pylint: disable=unused-import
from kraken.spot.funding import Funding
from kraken.spot.market import Market
from kraken.spot.orderbook import OrderbookClient
from kraken.spot.staking import Staking
from kraken.spot.trade import Trade
from kraken.spot.user import User
from kraken.spot.websocket_v1 import KrakenSpotWSClient
from kraken.spot.websocket_v2 import KrakenSpotWSClientV2

__all__ = [
    "Funding",
    "Market",
    "OrderbookClient",
    "Staking",
    "Trade",
    "User",
    "KrakenSpotWSClient",
    "KrakenSpotWSClientV2",
]

````

**Comment by btschwertfeger** [comment]
Hello @flynn1973, which version of the python-kraken-sdk are you using? 

I see that you're using Python 3.9. The latest version of the python-kraken-sdk does not support Python 3.9. 

You might have an older version of the package which does not implement the SpotAsyncClient.

**Comment by flynn1973** [comment]
hmm..i installed from pypi with pip...is the not synced with newest version?

**Comment by flynn1973** [comment]
ah ok, thank you!

**Comment by btschwertfeger** [comment]
You can view the version specific documentation at https://python-kraken-sdk.readthedocs.io/en/stable/ and then on the lower right you can switch which version to show.
