### ISSUE TITLE
Simple example doesn't work

### ISSUE THREAD

**Issue by emilamaj** [btschwertfeger/python-kraken-sdk#325]
**Describe the bug**
The simplest example in the readme doesn't work... recent refactoring that wasn't followed-thourgh in the documentation ?
In particular, I can't seem to find the correct namespace for the SpotClient

**To Reproduce**
Clean fresh install
Run the simple example
```python
from kraken.spot import SpotClient

client = SpotClient(key="<your-api-key>", secret="<your-secret-key>")
print(client.request("POST", "/0/private/Balance"))
```

**Expected behavior**
expected at least the import to work

**Environment (please complete the following information):**
python 3.10

**Comment by btschwertfeger** [comment]
Hello @emilamaj, which version of the SDK are you using? The current versions do not support Python 3.10.

**Comment by ancoron** [comment]
@btschwertfeger Encountered the same issue with Python 3.12.7 and the latest SDK 3.1.2

I've also tried the official examples from here: https://support.kraken.com/hc/en-us/articles/common-causes-of-invalid-key-error

None of those actually worked, so I am puzzled.

Is there a different API needed for clients from Germany due to the switch to DLT? If so, that would apply to me.

**Comment by emilamaj** [comment]
I'm fairly new with the Kraken API and I couldn't get to work any of their code examples so I had a chat with their support about it and they gave me a working example. Let me fetch it, maybe it's related

That being said, I'm surprised newer Python versions break the installs. Didn't somebody recently relocate the class SpotClient in the sdk ?

**Comment by ancoron** [comment]
@emilamaj The import works for me, I'm just getting this in all cases I've tried so far:
```
Traceback (most recent call last):
  File "/home/ancoron/dev/crypto-track/kraken_spot.py", line 7, in <module>
    print(client.request("POST", "/0/private/Balance"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ancoron/dev/crypto-track/.venv/lib/python3.12/site-packages/kraken/base_api/__init__.py", line 368, in request
    return self.__check_response_data(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ancoron/dev/crypto-track/.venv/lib/python3.12/site-packages/kraken/base_api/__init__.py", line 436, in __check_response_data
    return self._err_handler.check(data)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ancoron/dev/crypto-track/.venv/lib/python3.12/site-packages/kraken/base_api/__init__.py", line 130, in check
    raise exception(data)
kraken.exceptions.KrakenInvalidAPIKeyError: An invalid API-Key header was supplied.
```

**Comment by btschwertfeger** [comment]
> @btschwertfeger Encountered the same issue with Python 3.12.7 and the latest SDK 3.1.2
> 
> 
> 
> I've also tried the official examples from here: https://support.kraken.com/hc/en-us/articles/common-causes-of-invalid-key-error
> 
> 
> 
> None of those actually worked, so I am puzzled.
> 
> 
> 
> Is there a different API needed for clients from Germany due to the switch to DLT? If so, that would apply to me.

Did you created API keys and used these instead of these paceholders in the example?

**Comment by ancoron** [comment]
@btschwertfeger Yes, I've created new API keys for testing and activated these permissions:

* Funds permissions:
  * Query
* Orders and trades:
  * Query open orders & trades
  * Query closed orders & trades
* Data:
  * Query ledger entries
  * Export data

All the other options (WS, IP restrictions, ...) are off.

**Comment by emilamaj** [comment]
Did your keys work with the Kraken API until now ?

**Comment by btschwertfeger** [comment]
@ancoron, if the issue also persists using another tool than its most probably a Kraken account thing. Please let us know if you have further findings.

@emilamaj, is for you everything fine now?

**Comment by emilamaj** [comment]
@ancoron You seem to have the same strange issue I had for the last few days. I also tried this SDK to see wether it was my code or not.
I tried messing with various stuff like using a huge nonce window but to no avail.
As far as I know it either has to do with an additional account KYC imposed on EU accounts which make it seem like it is passed instantly but actually goes through  in the background (it can take a few days). Or there's some sort of admin lock on their side that the support can lift when you contact them.

@btschwertfeger I just tested everything on a new Python install and everything worked great! It was just an unsupported Python version issue paired with a Kraken thing.

**Comment by ancoron** [comment]
OK, mystery solved:

For some reason, the new Kraken API keys I generated gave me public keys that where only 36 bytes:
```bash
$ printf "2qH9Ax587CNBctJ439N1eZO0FTOkhWslskc35gwu3+zHZyXl" | base64 -d | wc -c
36
```

This then led to the "invalid key" error.

Just generated yet another API key and voila, it was 42 bytes as expected.

Problem solved for me.
