### ISSUE TITLE
Missing package (dotenv) in requirements.txt

### ISSUE THREAD

**Issue by jcr-jeff** [btschwertfeger/Python-Kraken-SDK#33]
Will keep this brief, rather than use the typical bug report format because it's simple.

Required package dotenv for the spot_ws_examples.py is missing from requirements.txt.  There may be packages missing, as I haven't taken a good look through the repository.

I also think that this is a somewhat unnecessary and non-standard method of retrieving variables from environment variables, and can probably be done away with to reduce unecessarry dependencies by just using 

`api_key = os.getenv('api_key')`
or
`api_key = os.environ.get('api_key')`

or some other more common alternative, but obviously it's your call :)

**Comment by btschwertfeger** [comment]
Hey @jcr-jeff, great thanks to you for the tip!

The modules for the examples are not included in the requirements for the SDK, as they are not relevant for the REST and websocket clients.

I will implement your suggested changes directly.
