### ISSUE TITLE
create_order() documentatoin for txid outdated.

### ISSUE THREAD

**Issue by andyDoucette** [btschwertfeger/python-kraken-sdk#96]
The documentation states that the result when you create an order has txid as a string:
```
trade.create_order(
    ordertype="market",
    side="buy",
    pair="XBTUSD",
    volume="0.0001"
)
{
    'txid': 'TNGMNU-XQSRA-LKCWOK',
    'descr': {
        'order': 'buy 4.00000000 XBTUSD @ limit 23000.0'
    }
}
```

Unfortunately, I'm getting a list, not a string.

The latest Kraken API documentatoin for /private/AddOrder states that txid is:
```
Transaction IDs for order
(if order was added successfully)
```

So, I think the documentation for create_order should probably be updated to reflect the fact that txid is now a list.

Thanks! :)

**Comment by btschwertfeger** [comment]
Hey @andyDoucette - you are right! I will adjust this in https://github.com/btschwertfeger/python-kraken-sdk/pull/95. Thanks too!
