### ISSUE TITLE
user.get_orders_info says it accepts a 'string containing a comma delimited list of txids' but it doesn't.

### ISSUE THREAD

**Issue by andyDoucette** [btschwertfeger/python-kraken-sdk#97]
The title says it all. :)

This does not work:
```
(Pdb) !info=user.get_orders_info("['OH56BN-YYV5I-A57HQZ']")
*** kraken.exceptions.KrakenException.KrakenInvalidOrderError: Order is invalid.
```

This does work:
```
(Pdb) !info=user.get_orders_info("OH56BN-YYV5I-A57HQZ")
```

It would be great if it accepted the stringified list because then you can make an order and look up it's status later.  It's confusing to me why an API would return a list of ids for a single creation of a single object.  I would expect to get an 'order_id" or something, not a list of things.

**Comment by btschwertfeger** [comment]
The description seems to be a bit misleading. it means that besides a single txid and a list like `["<orderId1>","<orderId2>"]` also a string is accepted which lists the order ids separated by commas: ´"<orderId1>,<orderId2>"`.

**Comment by andyDoucette** [comment]
That's what i understood.  The only issue is it doesn't work.

**Comment by btschwertfeger** [comment]
It is not planned to accept a string that looks like `"['XXX-XXX-XXX-0','XXX-XXX-XXX-1','XXX-XXX-XXX-2']"`, since the function already provides a parameter that accepts (a) unique orderId/txid, (b) a list of orderIds or txids, and (c) a string containing multiple ids separated by a comma. This is considered sufficient.

**Comment by andyDoucette** [comment]
ah, I see now.  For some reason I thought I was getting a string like that
from the create_order function, but it's possible it was something else in
my pipeline that was causing it to be a string.  That was a few days ago
and I've wiped my internal cache a few times since then. ;)

Anyway, thanks for your responsiveness!
